import { ClaimLineInsured, ClaimLineItem } from "../store/claimLineSlice";

export const REASON_OPTIONS = [
    { value: "", label: "----------" },
    { value: "1", label: "ไม่คุ้มครอง" },
    { value: "2", label: "เกินวงเงิน" },
    { value: "3", label: "ไม่ตรงเงื่อนไข" },
    { value: "4", label: "รอเอกสารเพิ่มเติม" },
];

export const mockClaimLineItems: ClaimLineItem[] = [
    // Pink group - IPD หลัก
    {
        id: "1",
        code: "1.1.12",
        description: "ค่าบริการการพยาบาลของผู้ประกอบวิชาชีพการพยาบาลและการผดุงครรภ์",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    {
        id: "2",
        code: "2.1.1",
        description: "ค่าห้องผู้ป่วยในทั่วไป",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    {
        id: "3",
        code: "2.3.1",
        description: "อาหารผู้ป่วยในปกติ",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    // Pink group - ICU
    {
        id: "4",
        code: "1.1.12 (2)",
        description: "ค่าบริการการพยาบาลของผู้ประกอบวิชาชีพการพยาบาลและการผดุงครรภ์ - ICU",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    {
        id: "5",
        code: "2.1.2",
        description: "ค่าห้อง ICU",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    {
        id: "6",
        code: "2.3.2(2)",
        description: "อาหารทางการแพทย์ - ICU",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    {
        id: "7",
        code: "2.3.3 (2)",
        description: "อาหารที่มีวัตถุประสงค์พิเศษอื่นๆ - ICU",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "pink",
        disabled: false,
    },
    // Yellow group
    {
        id: "8",
        code: "1.1.1 (1)",
        description: "ยาผู้ป่วยใน",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "9",
        code: "1.1.1 (2)",
        description: "ยาผู้ป่วยกลับบ้าน (ไม่เกิน 1,000 บาท)",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "10",
        code: "1.1.1(7)",
        description: "ค่าน้ำเกลือ",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "11",
        code: "1.1.10 (1)",
        description: "ค่าบริการทางกายภาพบำบัด (สาเหตุโดยตรงจากอุบัติเหตุ หรือเป็นการรักษาการเจ็บป่วยนั้นๆ โดยตรง)",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "12",
        code: "1.1.2(1)",
        description: "เวชภัณฑ์ 1",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "13",
        code: "1.1.2(3)",
        description: "เวชภัณฑ์ 3",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "14",
        code: "1.1.3",
        description: "ค่าบริการโลหิตและส่วนประกอบของโลหิต",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "15",
        code: "1.1.4",
        description: "ค่าตรวจวินิจฉัยทางเทคนิคการแพทย์และพยาธิวิทยา",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "16",
        code: "1.1.5.",
        description: "ค่าตรวจวินิจฉัยและการรักษาทางรังสีวิทยา (ไม่รวมค่าแพทย์)",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "17",
        code: "1.1.6",
        description: "ค่าตรวจวินิจฉัยโดยวิธีพิเศษอื่นๆ",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "18",
        code: "1.1.7(1)",
        description: "อุปกรณ์ของใช้และเครื่องมือที่ใช้นอกห้องผ่าตัด",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "19",
        code: "1.1.7(2)",
        description: "อุปกรณ์ของใช้และเครื่องมือที่ใช้ในห้องผ่าตัด",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "20",
        code: "1.1.8",
        description: "ค่าห้องผ่าตัดและห้องคลอด",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "21",
        code: "1.2.1(11)",
        description: "ค่าธรรมเนียมแพทย์สำหรับการตรวจวินิจฉัยสาขาเฉพาะ เช่น ค่าแพทย์อ่านฟิล์ม ค่าแพทย์ที่ปรึกษา",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "22",
        code: "1.2.3(1)",
        description: "ค่าปฏิบัติการอื่นๆ ของผู้ประกอบวิชาชีพ -- ค่าวิสัญญีแพทย์ และ/หรือวิสัญญีพยาบาล",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    {
        id: "23",
        code: "2.5 (1)",
        description: "ค่าบริการรถพยาบาลฉุกเฉิน (ตามความจำเป็นทางการแพทย์) (ไม่เกิน 1,000 บาท)",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "yellow",
        disabled: false,
    },
    // Purple group
    {
        id: "24",
        code: "1.2.2",
        description: "ค่าทำศัลยกรรมและหัตถการต่างๆ ของผู้ประกอบวิชาชีพ",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "purple",
        disabled: false,
    },
    // Green group (Ex-gratia)
    {
        id: "25",
        code: "Ex1",
        description: "(Ex-gratia) อุปกรณ์ของใช้และเครื่องมือที่ใช้ในห้องผ่าตัด",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "green",
        disabled: false,
    },
    {
        id: "26",
        code: "Ex2",
        description: "(Ex-gratia) ค่าห้องผ่าตัดและห้องคลอด",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "green",
        disabled: false,
    },
    {
        id: "27",
        code: "Ex3",
        description: "(Ex-gratia) ค่าปฏิบัติการอื่นๆ ของผู้ประกอบวิชาชีพ -- ค่าวิสัญญีแพทย์ และ/หรือวิสัญญีพยาบาล",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "green",
        disabled: false,
    },
    // Cyan group
    {
        id: "28",
        code: "1.2.1(1)-(10)",
        description: "ค่าตรวจรักษาทั่วไปของผู้ประกอบวิชาชีพแพทย์ (ยกเว้นนิติเวช)",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "cyan",
        disabled: false,
    },
    // Gray group (disabled)
    {
        id: "29",
        code: "1.1.10 (2)",
        description: "ค่าบริการทางกายภาพบำบัด (ไม่สัมพันธ์กับอาการหรือโรคที่เข้ารับการรักษาครั้งนั้น ๆ)",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "gray",
        disabled: true,
    },
    {
        id: "30",
        code: "1.1.11",
        description: "ค่าบริการฝังเข็ม",
        claimAmount: "",
        discount: "",
        notCovered: "",
        reason: "",
        remark: "",
        color: "gray",
        disabled: true,
    },
];

export interface TreatmentTypeOption {
    CaseTypeId: number;
    CaseTypeName: string;
}

export const TREATMENT_TYPE_OPTIONS: TreatmentTypeOption[] = [
    { CaseTypeId: 2, CaseTypeName: "IPD" },
    { CaseTypeId: 3, CaseTypeName: "OPD" },
    { CaseTypeId: 4, CaseTypeName: "DAY_Surgery" },
    { CaseTypeId: 5, CaseTypeName: "DeathCase" },
    { CaseTypeId: 6, CaseTypeName: "Disability" },
];

export const CONTINUOUS_CLAIM_OPTIONS = [
    { value: "CL2024001", label: "CL2024001 - 01/03/2567" },
    { value: "CL2024002", label: "CL2024002 - 15/03/2567" },
];

export const mockInsuredSearchResults: ClaimLineInsured[] = [
    {
        appId: "9199293",
        prefix: "เด็กชาย",
        firstName: "ชลชาติ",
        lastName: "รุกขชาติ",
        nationalId: "1-6299-00964-54-6",
        plan: "502-Silver+",
        status: "ปกติ",
        startCoverDate: "2017-05-01",
        cancelDate: "",
        company: "บริษัท อาคเนย์ประกันภัย จำกัด(มหาชน)",
    },
    {
        appId: "9199293-P30-01",
        prefix: "เด็กชาย",
        firstName: "ชลชาติ",
        lastName: "รุกขชาติ",
        nationalId: "1-6299-00964-54-6",
        plan: "P30",
        status: "ปกติ",
        startCoverDate: "2017-05-01",
        cancelDate: "",
        company: "บริษัท อาคเนย์ประกันภัย จำกัด(มหาชน)",
    },
];
