//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { customFormatter } from "../modules/_common/commonFunctions";
import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from "axios";

import * as dayjs from "dayjs";

export class CoreClaimClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * API สำหรับ Calculate ข้อมูล Case Claim
     * @param body (optional)
     * @return Success
     */
    calculateCaseClaim(
        body?: CalculateCaseClaimDtoRequest | undefined,
        cancelToken?: CancelToken | undefined
    ): Promise<CalculateCaseClaimDtoResponseServiceResponse> {
        let url_ = this.baseUrl + "/calculate/caseclaim";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body, customFormatter);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json-patch+json",
                Accept: "text/plain",
            },
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processCalculateCaseClaim(_response);
            });
    }

    protected processCalculateCaseClaim(
        response: AxiosResponse
    ): Promise<CalculateCaseClaimDtoResponseServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = resultData200;
            return Promise.resolve<CalculateCaseClaimDtoResponseServiceResponse>(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CalculateCaseClaimDtoResponseServiceResponse>(null as any);
    }
}

export class IClaimClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * API สำหรับ Get ข้อมูล เช็คสิทธิ์ความคุ้มครอง
     * @param hospitalCode (optional)
     * @param claimType (optional)
     * @param episodeType (optional)
     * @param incurredDate (optional)
     * @param incurredTime (optional)
     * @param incidentDate (optional)
     * @param incidentTime (optional)
     * @param claimFromMotorcycle (optional)
     * @param searchOptionId (optional)
     * @param userName (optional)
     * @param cIDPassport (optional)
     * @param iD (optional)
     * @param insurerCode (optional)
     * @param policyNumber (optional)
     * @param causeOfAccident (optional)
     * @param applicationCode (optional)
     * @param name (optional)
     * @param surName (optional)
     * @param birthDate (optional)
     * @return Success
     */
    checkEligible(
        iClaimToken: string,
        hospitalCode?: string | undefined,
        claimType?: string | undefined,
        episodeType?: string | undefined,
        incurredDate?: dayjs.Dayjs | undefined,
        incurredTime?: dayjs.Dayjs | undefined,
        incidentDate?: dayjs.Dayjs | undefined,
        incidentTime?: dayjs.Dayjs | undefined,
        claimFromMotorcycle?: boolean | undefined,
        searchOptionId?: number | undefined,
        userName?: string | undefined,
        cIDPassport?: string | undefined,
        iD?: string | undefined,
        insurerCode?: string | undefined,
        policyNumber?: string | undefined,
        causeOfAccident?: string | undefined,
        applicationCode?: string | undefined,
        name?: string | undefined,
        surName?: string | undefined,
        birthDate?: dayjs.Dayjs | undefined,
        cancelToken?: CancelToken | undefined
    ): Promise<CheckEligibleDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/IClaim/check-eligible?";
        if (hospitalCode === null) throw new Error("The parameter 'hospitalCode' cannot be null.");
        else if (hospitalCode !== undefined) url_ += "HospitalCode=" + encodeURIComponent("" + hospitalCode) + "&";
        if (claimType === null) throw new Error("The parameter 'claimType' cannot be null.");
        else if (claimType !== undefined) url_ += "ClaimType=" + encodeURIComponent("" + claimType) + "&";
        if (episodeType === null) throw new Error("The parameter 'episodeType' cannot be null.");
        else if (episodeType !== undefined) url_ += "EpisodeType=" + encodeURIComponent("" + episodeType) + "&";
        if (incurredDate === null) throw new Error("The parameter 'incurredDate' cannot be null.");
        else if (incurredDate !== undefined)
            url_ +=
                "IncurredDate=" +
                encodeURIComponent(incurredDate ? "" + incurredDate.format("YYYY-MM-DDTHH:mm:ss") : "") +
                "&";
        if (incurredTime === null) throw new Error("The parameter 'incurredTime' cannot be null.");
        else if (incurredTime !== undefined)
            url_ +=
                "IncurredTime=" +
                encodeURIComponent(incurredTime ? "" + incurredTime.format("YYYY-MM-DDTHH:mm:ss") : "") +
                "&";
        if (incidentDate === null) throw new Error("The parameter 'incidentDate' cannot be null.");
        else if (incidentDate !== undefined)
            url_ +=
                "IncidentDate=" +
                encodeURIComponent(incidentDate ? "" + incidentDate.format("YYYY-MM-DDTHH:mm:ss") : "") +
                "&";
        if (incidentTime === null) throw new Error("The parameter 'incidentTime' cannot be null.");
        else if (incidentTime !== undefined)
            url_ +=
                "IncidentTime=" +
                encodeURIComponent(incidentTime ? "" + incidentTime.format("YYYY-MM-DDTHH:mm:ss") : "") +
                "&";
        if (claimFromMotorcycle === null) throw new Error("The parameter 'claimFromMotorcycle' cannot be null.");
        else if (claimFromMotorcycle !== undefined)
            url_ += "ClaimFromMotorcycle=" + encodeURIComponent("" + claimFromMotorcycle) + "&";
        if (searchOptionId === null) throw new Error("The parameter 'searchOptionId' cannot be null.");
        else if (searchOptionId !== undefined)
            url_ += "SearchOptionId=" + encodeURIComponent("" + searchOptionId) + "&";
        if (userName === null) throw new Error("The parameter 'userName' cannot be null.");
        else if (userName !== undefined) url_ += "UserName=" + encodeURIComponent("" + userName) + "&";
        if (cIDPassport === null) throw new Error("The parameter 'cIDPassport' cannot be null.");
        else if (cIDPassport !== undefined) url_ += "CIDPassport=" + encodeURIComponent("" + cIDPassport) + "&";
        if (iD === null) throw new Error("The parameter 'iD' cannot be null.");
        else if (iD !== undefined) url_ += "ID=" + encodeURIComponent("" + iD) + "&";
        if (insurerCode === null) throw new Error("The parameter 'insurerCode' cannot be null.");
        else if (insurerCode !== undefined) url_ += "InsurerCode=" + encodeURIComponent("" + insurerCode) + "&";
        if (policyNumber === null) throw new Error("The parameter 'policyNumber' cannot be null.");
        else if (policyNumber !== undefined) url_ += "PolicyNumber=" + encodeURIComponent("" + policyNumber) + "&";
        if (causeOfAccident === null) throw new Error("The parameter 'causeOfAccident' cannot be null.");
        else if (causeOfAccident !== undefined)
            url_ += "CauseOfAccident=" + encodeURIComponent("" + causeOfAccident) + "&";
        if (applicationCode === null) throw new Error("The parameter 'applicationCode' cannot be null.");
        else if (applicationCode !== undefined)
            url_ += "ApplicationCode=" + encodeURIComponent("" + applicationCode) + "&";
        if (name === null) throw new Error("The parameter 'name' cannot be null.");
        else if (name !== undefined) url_ += "Name=" + encodeURIComponent("" + name) + "&";
        if (surName === null) throw new Error("The parameter 'surName' cannot be null.");
        else if (surName !== undefined) url_ += "SurName=" + encodeURIComponent("" + surName) + "&";
        if (birthDate === null) throw new Error("The parameter 'birthDate' cannot be null.");
        else if (birthDate !== undefined)
            url_ +=
                "BirthDate=" + encodeURIComponent(birthDate ? "" + birthDate.format("YYYY-MM-DDTHH:mm:ss") : "") + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                IClaimToken: iClaimToken !== undefined && iClaimToken !== null ? "" + iClaimToken : "",
                Accept: "text/plain",
            },
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processCheckEligible(_response);
            });
    }

    protected processCheckEligible(response: AxiosResponse): Promise<CheckEligibleDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = resultData200;
            return Promise.resolve<CheckEligibleDtoResponseListServiceResponse>(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CheckEligibleDtoResponseListServiceResponse>(null as any);
    }
}

export class MastersClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {
        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * API สำหรับ Get ข้อมูลพนักงาน
     * @param userId (optional)
     * @return Success
     */
    users(
        userId?: number | undefined,
        cancelToken?: CancelToken | undefined
    ): Promise<AllUserDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/Masters/users?";
        if (userId === null) throw new Error("The parameter 'userId' cannot be null.");
        else if (userId !== undefined) url_ += "userId=" + encodeURIComponent("" + userId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                Accept: "text/plain",
            },
            cancelToken,
        };

        return this.instance
            .request(options_)
            .catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            })
            .then((_response: AxiosResponse) => {
                return this.processUsers(_response);
            });
    }

    protected processUsers(response: AxiosResponse): Promise<AllUserDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200 = _responseText;
            result200 = resultData200;
            return Promise.resolve<AllUserDtoResponseListServiceResponse>(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AllUserDtoResponseListServiceResponse>(null as any);
    }
}

export interface AllUserDtoResponse {
    userId?: number | undefined;
    employeeId?: number;
    personId?: number | undefined;
    employeeCode?: string | undefined;
    titleId?: number | undefined;
    titleCode?: string | undefined;
    titleName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    personName?: string | undefined;
    teamId?: number | undefined;
    teamCode?: string | undefined;
    teamName?: string | undefined;
    branchId?: number | undefined;
    branchName?: string | undefined;
    employeeStatusId?: number | undefined;
    employeeStatus?: string | undefined;
    positionId?: number | undefined;
    departmentId?: number | undefined;
    phoneNo?: string | undefined;
}

export interface AllUserDtoResponseListServiceResponse {
    data?: AllUserDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface CalculateCaseClaimDtoRequest {
    caseId?: string;
    isSimulateCase?: boolean;
    jsonDetail?: CalculateCaseClaimItem[] | undefined;
}

export interface CalculateCaseClaimDtoResponse {
    medicalExpense?: MedicalExpenseList[] | undefined;
    compensateExpense?: string | undefined;
    medicalNet?: number;
    medicalPay?: number;
    summaryMedicalPay?: number;
    summaryMedicalUnPay?: number;
}

export interface CalculateCaseClaimDtoResponseServiceResponse {
    data?: CalculateCaseClaimDtoResponse;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface CalculateCaseClaimItem {
    id?: number;
    code?: string | undefined;
    description?: string | undefined;
    claimAmount?: number;
    discount?: number;
    notCovered?: number;
    reason?: string | undefined;
    remark?: string | undefined;
}

export interface CheckEligibleDtoResponse {
    checkeligibleId?: string | undefined;
    applicationCode?: string | undefined;
    customerDetail_id?: string | undefined;
    refID?: string | undefined;
    transactionNo?: string | undefined;
    hospitalCode?: string | undefined;
    insurerCode?: string | undefined;
    identityId?: string | undefined;
    passportCardID?: string | undefined;
    dob?: dayjs.Dayjs | undefined;
    policyNumber?: string | undefined;
    titleName?: string | undefined;
    firstName?: string | undefined;
    midName?: string | undefined;
    lastName?: string | undefined;
    planCode?: string | undefined;
    planName?: string | undefined;
    insuranceIDType?: string | undefined;
    insuranceType?: string | undefined;
    episodeType?: string | undefined;
    serviceType?: string | undefined;
    effectiveDate?: dayjs.Dayjs | undefined;
    effectiveTime?: string | undefined;
    expireDate?: dayjs.Dayjs | undefined;
    expireTime?: string | undefined;
    coverageStatusCode?: string | undefined;
    coverageStatus?: string | undefined;
    coverageClaimStatusCode?: string | undefined;
    coverageClaimStatus?: string | undefined;
    coverageClaimRemark?: string | undefined;
    benefitName?: string | undefined;
    benefitAmount?: number | undefined;
    benefitTimes?: string | undefined;
    benefitDays?: string | undefined;
    benefitEmergencyHours?: string | undefined;
    benefitCoPaymentPercentage?: string | undefined;
    benefitTimesPerDay?: string | undefined;
    consumeBenefitAmount?: string | undefined;
    consumeBenefitTimes?: string | undefined;
    consumeBenefitDays?: string | undefined;
    consumeBenefitTimesPerDay?: string | undefined;
    exclusionProduct?: string | undefined;
    exclusionPolicy?: string | undefined;
    exclusionPersonal?: string | undefined;
    createdDate?: dayjs.Dayjs | undefined;
    updatedDate?: dayjs.Dayjs | undefined;
    benefitCode?: string | undefined;
    claimExpenseCode?: string | undefined;
    claimExpenseDetail?: string | undefined;
    simbCode?: string | undefined;
    simbDescriptionTH?: string | undefined;
    simbDescriptionEN?: string | undefined;
}

export interface CheckEligibleDtoResponseListServiceResponse {
    data?: CheckEligibleDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface MedicalExpenseList {
    expenseCategoryName?: string | undefined;
    benefitName?: string | undefined;
    coveredAmount?: number;
    nonCoveredAmount?: number;
    totalAmount?: number;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result?: any
): any {
    if (result !== null && result !== undefined) throw result;
    else throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any | undefined): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}
