//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { customFormatter } from "../modules/_common/commonFunctions";
import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import * as dayjs from 'dayjs';

export class CoreClaimClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }

    /**
     * API สำหรับ Search Customer
     * @param searchIndex (optional) 
     * @param isSeachDetail (optional) 
     * @param dateHappen (optional) 
     * @param schoolId (optional) 
     * @param provinceId (optional) 
     * @param incidentTypeId (optional) 
     * @param searchDetail (optional) 
     * @param orderingField (optional) 
     * @param ascendingOrder (optional) 
     * @param page (optional) 
     * @param recordsPerPage (optional) 
     * @return Success
     */
    getCustomerSearch(searchIndex?: number | undefined, isSeachDetail?: boolean | undefined, dateHappen?: dayjs.Dayjs | undefined, schoolId?: number | undefined, provinceId?: number | undefined, incidentTypeId?: number | undefined, searchDetail?: string | undefined, orderingField?: string | undefined, ascendingOrder?: boolean | undefined, page?: number | undefined, recordsPerPage?: number | undefined, cancelToken?: CancelToken | undefined): Promise<GetCustomerSearchDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/customer/search?";
        if (searchIndex === null)
            throw new Error("The parameter 'searchIndex' cannot be null.");
        else if (searchIndex !== undefined)
            url_ += "searchIndex=" + encodeURIComponent("" + searchIndex) + "&";
        if (isSeachDetail === null)
            throw new Error("The parameter 'isSeachDetail' cannot be null.");
        else if (isSeachDetail !== undefined)
            url_ += "isSeachDetail=" + encodeURIComponent("" + isSeachDetail) + "&";
        if (dateHappen === null)
            throw new Error("The parameter 'dateHappen' cannot be null.");
        else if (dateHappen !== undefined)
            url_ += "dateHappen=" + encodeURIComponent(dateHappen ? "" + dateHappen.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        if (schoolId === null)
            throw new Error("The parameter 'schoolId' cannot be null.");
        else if (schoolId !== undefined)
            url_ += "schoolId=" + encodeURIComponent("" + schoolId) + "&";
        if (provinceId === null)
            throw new Error("The parameter 'provinceId' cannot be null.");
        else if (provinceId !== undefined)
            url_ += "provinceId=" + encodeURIComponent("" + provinceId) + "&";
        if (incidentTypeId === null)
            throw new Error("The parameter 'incidentTypeId' cannot be null.");
        else if (incidentTypeId !== undefined)
            url_ += "incidentTypeId=" + encodeURIComponent("" + incidentTypeId) + "&";
        if (searchDetail === null)
            throw new Error("The parameter 'searchDetail' cannot be null.");
        else if (searchDetail !== undefined)
            url_ += "searchDetail=" + encodeURIComponent("" + searchDetail) + "&";
        if (orderingField === null)
            throw new Error("The parameter 'orderingField' cannot be null.");
        else if (orderingField !== undefined)
            url_ += "orderingField=" + encodeURIComponent("" + orderingField) + "&";
        if (ascendingOrder === null)
            throw new Error("The parameter 'ascendingOrder' cannot be null.");
        else if (ascendingOrder !== undefined)
            url_ += "ascendingOrder=" + encodeURIComponent("" + ascendingOrder) + "&";
        if (page === null)
            throw new Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "Page=" + encodeURIComponent("" + page) + "&";
        if (recordsPerPage === null)
            throw new Error("The parameter 'recordsPerPage' cannot be null.");
        else if (recordsPerPage !== undefined)
            url_ += "recordsPerPage=" + encodeURIComponent("" + recordsPerPage) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetCustomerSearch(_response);
        });
    }

    protected processGetCustomerSearch(response: AxiosResponse): Promise<GetCustomerSearchDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<GetCustomerSearchDtoResponseListServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GetCustomerSearchDtoResponseListServiceResponse>(null as any);
    }

    /**
     * API สำหรับ Get ข้อมูล Customer Detail By Id
     * @return Success
     */
    getCustomerDetailById(id: number, cancelToken?: CancelToken | undefined): Promise<GetCustomerDetailByIdDtoResponseServiceResponse> {
        let url_ = this.baseUrl + "/customer/{id}/detail";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetCustomerDetailById(_response);
        });
    }

    protected processGetCustomerDetailById(response: AxiosResponse): Promise<GetCustomerDetailByIdDtoResponseServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<GetCustomerDetailByIdDtoResponseServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GetCustomerDetailByIdDtoResponseServiceResponse>(null as any);
    }

    /**
     * API สำหรับ Search Customer Benefit Detail
     * @param policyCode (optional) 
     * @param caseTypeId (optional) 
     * @param dateHappen (optional) 
     * @param isContinue (optional) 
     * @return Success
     */
    getCustomerBenefitDetailSearch(policyCode?: string | undefined, caseTypeId?: number | undefined, dateHappen?: dayjs.Dayjs | undefined, isContinue?: boolean | undefined, cancelToken?: CancelToken | undefined): Promise<GetCustomerBenefitDetailSearchDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/customer/benefit-detail/search?";
        if (policyCode === null)
            throw new Error("The parameter 'policyCode' cannot be null.");
        else if (policyCode !== undefined)
            url_ += "policyCode=" + encodeURIComponent("" + policyCode) + "&";
        if (caseTypeId === null)
            throw new Error("The parameter 'caseTypeId' cannot be null.");
        else if (caseTypeId !== undefined)
            url_ += "caseTypeId=" + encodeURIComponent("" + caseTypeId) + "&";
        if (dateHappen === null)
            throw new Error("The parameter 'dateHappen' cannot be null.");
        else if (dateHappen !== undefined)
            url_ += "dateHappen=" + encodeURIComponent(dateHappen ? "" + dateHappen.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        if (isContinue === null)
            throw new Error("The parameter 'isContinue' cannot be null.");
        else if (isContinue !== undefined)
            url_ += "isContinue=" + encodeURIComponent("" + isContinue) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetCustomerBenefitDetailSearch(_response);
        });
    }

    protected processGetCustomerBenefitDetailSearch(response: AxiosResponse): Promise<GetCustomerBenefitDetailSearchDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<GetCustomerBenefitDetailSearchDtoResponseListServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GetCustomerBenefitDetailSearchDtoResponseListServiceResponse>(null as any);
    }

    /**
     * API สำหรับ Calculate ข้อมูล Case Claim
     * @param body (optional) 
     * @return Success
     */
    calculateCaseClaim(body?: CalculateCaseClaimDtoRequest | undefined, cancelToken?: CancelToken | undefined): Promise<CalculateCaseClaimDtoResponseServiceResponse> {
        let url_ = this.baseUrl + "/calculate/caseclaim";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body, customFormatter);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCalculateCaseClaim(_response);
        });
    }

    protected processCalculateCaseClaim(response: AxiosResponse): Promise<CalculateCaseClaimDtoResponseServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<CalculateCaseClaimDtoResponseServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CalculateCaseClaimDtoResponseServiceResponse>(null as any);
    }
}

export class IClaimClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }

    /**
     * API สำหรับ Get ข้อมูล เช็คสิทธิ์ความคุ้มครอง
     * @param hospitalCode (optional) 
     * @param claimType (optional) 
     * @param episodeType (optional) 
     * @param incurredDate (optional) 
     * @param incurredTime (optional) 
     * @param incidentDate (optional) 
     * @param incidentTime (optional) 
     * @param claimFromMotorcycle (optional) 
     * @param searchOptionId (optional) 
     * @param userName (optional) 
     * @param cIDPassport (optional) 
     * @param iD (optional) 
     * @param insurerCode (optional) 
     * @param policyNumber (optional) 
     * @param causeOfAccident (optional) 
     * @param applicationCode (optional) 
     * @param name (optional) 
     * @param surName (optional) 
     * @param birthDate (optional) 
     * @return Success
     */
    checkEligible(iClaimToken: string, hospitalCode?: string | undefined, claimType?: string | undefined, episodeType?: string | undefined, incurredDate?: dayjs.Dayjs | undefined, incurredTime?: dayjs.Dayjs | undefined, incidentDate?: dayjs.Dayjs | undefined, incidentTime?: dayjs.Dayjs | undefined, claimFromMotorcycle?: boolean | undefined, searchOptionId?: number | undefined, userName?: string | undefined, cIDPassport?: string | undefined, iD?: string | undefined, insurerCode?: string | undefined, policyNumber?: string | undefined, causeOfAccident?: string | undefined, applicationCode?: string | undefined, name?: string | undefined, surName?: string | undefined, birthDate?: dayjs.Dayjs | undefined, cancelToken?: CancelToken | undefined): Promise<CheckEligibleDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/IClaim/check-eligible?";
        if (hospitalCode === null)
            throw new Error("The parameter 'hospitalCode' cannot be null.");
        else if (hospitalCode !== undefined)
            url_ += "HospitalCode=" + encodeURIComponent("" + hospitalCode) + "&";
        if (claimType === null)
            throw new Error("The parameter 'claimType' cannot be null.");
        else if (claimType !== undefined)
            url_ += "ClaimType=" + encodeURIComponent("" + claimType) + "&";
        if (episodeType === null)
            throw new Error("The parameter 'episodeType' cannot be null.");
        else if (episodeType !== undefined)
            url_ += "EpisodeType=" + encodeURIComponent("" + episodeType) + "&";
        if (incurredDate === null)
            throw new Error("The parameter 'incurredDate' cannot be null.");
        else if (incurredDate !== undefined)
            url_ += "IncurredDate=" + encodeURIComponent(incurredDate ? "" + incurredDate.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        if (incurredTime === null)
            throw new Error("The parameter 'incurredTime' cannot be null.");
        else if (incurredTime !== undefined)
            url_ += "IncurredTime=" + encodeURIComponent(incurredTime ? "" + incurredTime.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        if (incidentDate === null)
            throw new Error("The parameter 'incidentDate' cannot be null.");
        else if (incidentDate !== undefined)
            url_ += "IncidentDate=" + encodeURIComponent(incidentDate ? "" + incidentDate.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        if (incidentTime === null)
            throw new Error("The parameter 'incidentTime' cannot be null.");
        else if (incidentTime !== undefined)
            url_ += "IncidentTime=" + encodeURIComponent(incidentTime ? "" + incidentTime.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        if (claimFromMotorcycle === null)
            throw new Error("The parameter 'claimFromMotorcycle' cannot be null.");
        else if (claimFromMotorcycle !== undefined)
            url_ += "ClaimFromMotorcycle=" + encodeURIComponent("" + claimFromMotorcycle) + "&";
        if (searchOptionId === null)
            throw new Error("The parameter 'searchOptionId' cannot be null.");
        else if (searchOptionId !== undefined)
            url_ += "SearchOptionId=" + encodeURIComponent("" + searchOptionId) + "&";
        if (userName === null)
            throw new Error("The parameter 'userName' cannot be null.");
        else if (userName !== undefined)
            url_ += "UserName=" + encodeURIComponent("" + userName) + "&";
        if (cIDPassport === null)
            throw new Error("The parameter 'cIDPassport' cannot be null.");
        else if (cIDPassport !== undefined)
            url_ += "CIDPassport=" + encodeURIComponent("" + cIDPassport) + "&";
        if (iD === null)
            throw new Error("The parameter 'iD' cannot be null.");
        else if (iD !== undefined)
            url_ += "ID=" + encodeURIComponent("" + iD) + "&";
        if (insurerCode === null)
            throw new Error("The parameter 'insurerCode' cannot be null.");
        else if (insurerCode !== undefined)
            url_ += "InsurerCode=" + encodeURIComponent("" + insurerCode) + "&";
        if (policyNumber === null)
            throw new Error("The parameter 'policyNumber' cannot be null.");
        else if (policyNumber !== undefined)
            url_ += "PolicyNumber=" + encodeURIComponent("" + policyNumber) + "&";
        if (causeOfAccident === null)
            throw new Error("The parameter 'causeOfAccident' cannot be null.");
        else if (causeOfAccident !== undefined)
            url_ += "CauseOfAccident=" + encodeURIComponent("" + causeOfAccident) + "&";
        if (applicationCode === null)
            throw new Error("The parameter 'applicationCode' cannot be null.");
        else if (applicationCode !== undefined)
            url_ += "ApplicationCode=" + encodeURIComponent("" + applicationCode) + "&";
        if (name === null)
            throw new Error("The parameter 'name' cannot be null.");
        else if (name !== undefined)
            url_ += "Name=" + encodeURIComponent("" + name) + "&";
        if (surName === null)
            throw new Error("The parameter 'surName' cannot be null.");
        else if (surName !== undefined)
            url_ += "SurName=" + encodeURIComponent("" + surName) + "&";
        if (birthDate === null)
            throw new Error("The parameter 'birthDate' cannot be null.");
        else if (birthDate !== undefined)
            url_ += "BirthDate=" + encodeURIComponent(birthDate ? "" + birthDate.format('YYYY-MM-DDTHH:mm:ss') : "") + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "IClaimToken": iClaimToken !== undefined && iClaimToken !== null ? "" + iClaimToken : "",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCheckEligible(_response);
        });
    }

    protected processCheckEligible(response: AxiosResponse): Promise<CheckEligibleDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<CheckEligibleDtoResponseListServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CheckEligibleDtoResponseListServiceResponse>(null as any);
    }
}

export class MastersClient {
    private instance: AxiosInstance;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance ? instance : axios.create();

        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";

    }

    /**
     * API สำหรับ Get ข้อมูลพนักงาน
     * @param userId (optional) 
     * @return Success
     */
    users(userId?: number | undefined, cancelToken?: CancelToken | undefined): Promise<AllUserDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/Masters/users?";
        if (userId === null)
            throw new Error("The parameter 'userId' cannot be null.");
        else if (userId !== undefined)
            url_ += "userId=" + encodeURIComponent("" + userId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUsers(_response);
        });
    }

    protected processUsers(response: AxiosResponse): Promise<AllUserDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<AllUserDtoResponseListServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AllUserDtoResponseListServiceResponse>(null as any);
    }

    /**
     * API สำหรับ Get ข้อมูล MedicalType
     * @param claimSourceId (optional) 
     * @return Success
     */
    getMedicalType(claimSourceId?: number | undefined, cancelToken?: CancelToken | undefined): Promise<MedicalTypeDtoResponseListServiceResponse> {
        let url_ = this.baseUrl + "/Masters/medicaltype?";
        if (claimSourceId === null)
            throw new Error("The parameter 'claimSourceId' cannot be null.");
        else if (claimSourceId !== undefined)
            url_ += "claimSourceId=" + encodeURIComponent("" + claimSourceId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetMedicalType(_response);
        });
    }

    protected processGetMedicalType(response: AxiosResponse): Promise<MedicalTypeDtoResponseListServiceResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (let k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<MedicalTypeDtoResponseListServiceResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<MedicalTypeDtoResponseListServiceResponse>(null as any);
    }
}

export interface AllUserDtoResponse {
    userId?: number | undefined;
    employeeId?: number;
    personId?: number | undefined;
    employeeCode?: string | undefined;
    titleId?: number | undefined;
    titleCode?: string | undefined;
    titleName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    personName?: string | undefined;
    teamId?: number | undefined;
    teamCode?: string | undefined;
    teamName?: string | undefined;
    branchId?: number | undefined;
    branchName?: string | undefined;
    employeeStatusId?: number | undefined;
    employeeStatus?: string | undefined;
    positionId?: number | undefined;
    departmentId?: number | undefined;
    phoneNo?: string | undefined;
    displayName?: string | undefined;
}

export interface AllUserDtoResponseListServiceResponse {
    data?: AllUserDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface CalculateCaseClaim {
    productId?: number;
    patianTypeId?: number;
    caseTypeId?: number;
    icuCount?: number | undefined;
    dateHappen?: dayjs.Dayjs | undefined;
    dateIn?: dayjs.Dayjs | undefined;
    dateOut?: dayjs.Dayjs | undefined;
    expenseList?: CalculateCaseClaimItem[] | undefined;
}

export interface CalculateCaseClaimDtoRequest {
    caseId?: string;
    isSimulateCase?: boolean;
    jsonDetail?: CalculateCaseClaim;
}

export interface CalculateCaseClaimDtoResponse {
    medicalExpense?: MedicalExpenseList[] | undefined;
    compensateExpense?: CompensateExpenseList[] | undefined;
    medicalNet?: number;
    medicalPay?: number;
    summaryMedicalPay?: number;
    summaryMedicalUnPay?: number;
}

export interface CalculateCaseClaimDtoResponseServiceResponse {
    data?: CalculateCaseClaimDtoResponse;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface CalculateCaseClaimItem {
    code?: string | undefined;
    description?: string | undefined;
    claimAmount?: number;
    discount?: number;
    notCovered?: number;
    reason?: string | undefined;
    remark?: string | undefined;
}

export interface CheckEligibleDtoResponse {
}

export interface CheckEligibleDtoResponseListServiceResponse {
    data?: CheckEligibleDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface CompensateExpenseList {
    benefit_id?: string | undefined;
    benefit_Detail?: string | undefined;
    net?: number;
    cover?: number;
    unCover?: number;
    pay?: number;
    unPay?: number;
    countDay?: number;
    dayOfUnit?: number;
}

export interface GetCustomerBenefitDetailSearchDtoResponse {
    productName?: string | undefined;
    coverageFrom?: dayjs.Dayjs | undefined;
    coverageTo?: dayjs.Dayjs | undefined;
    benefitName?: string | undefined;
    pricePerUnit?: number | undefined;
    unitName?: string | undefined;
    maxQuantity?: number | undefined;
    quantityUnitName?: string | undefined;
    maxPrice?: number | undefined;
    customerTypeCode?: string | undefined;
    remainBenefit?: number | undefined;
    benefitId?: number | undefined;
}

export interface GetCustomerBenefitDetailSearchDtoResponseListServiceResponse {
    data?: GetCustomerBenefitDetailSearchDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface GetCustomerDetailByIdDtoResponse {
    policyCode?: string | undefined;
    customerName?: string | undefined;
    cardDetail?: string | undefined;
    productTypeName?: string | undefined;
    productName?: string | undefined;
    coverageFrom?: dayjs.Dayjs | undefined;
    coverageTo?: dayjs.Dayjs | undefined;
    customerCode?: string | undefined;
    schoolName?: string | undefined;
    provinceName?: string | undefined;
    districtName?: string | undefined;
    subDistrictName?: string | undefined;
    address?: string | undefined;
    mobilePhoneNumber?: string | undefined;
    birthDate?: dayjs.Dayjs | undefined;
    genderName?: string | undefined;
    occupationName?: string | undefined;
    titleName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
}

export interface GetCustomerDetailByIdDtoResponseServiceResponse {
    data?: GetCustomerDetailByIdDtoResponse;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface GetCustomerSearchDtoResponse {
    id?: number;
    cardTypeId?: number | undefined;
    cardDetail?: string | undefined;
    customerName?: string | undefined;
    productTypeId?: number | undefined;
    productTypeName?: string | undefined;
    policyCode?: string | undefined;
    customerCode?: string | undefined;
    appStatusId?: number | undefined;
    coverageFrom?: dayjs.Dayjs | undefined;
    coverageTo?: dayjs.Dayjs | undefined;
    productName?: string | undefined;
    schoolName?: string | undefined;
    totalCount?: number | undefined;
    mobilePhoneNumber?: string | undefined;
}

export interface GetCustomerSearchDtoResponseListServiceResponse {
    data?: GetCustomerSearchDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export interface MedicalExpenseList {
    benefit_id?: string | undefined;
    benefit_Detail?: string | undefined;
    net?: number;
    cover?: number;
    unCover?: number;
    pay?: number;
    unPay?: number;
}

export interface MedicalTypeDtoResponse {
    medicalTypeId?: number;
    medicalTypeName?: string | undefined;
}

export interface MedicalTypeDtoResponseListServiceResponse {
    data?: MedicalTypeDtoResponse[] | undefined;
    isSuccess?: boolean;
    message?: string | undefined;
    code?: number | undefined;
    exceptionMessage?: any | undefined;
    serverDateTime?: dayjs.Dayjs;
    totalAmountRecords?: number | undefined;
    totalAmountPages?: number | undefined;
    currentPage?: number | undefined;
    recordsPerPage?: number | undefined;
    pageIndex?: number | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any | undefined): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}